# Generated by Django 3.0.7 on 2021-02-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20210207_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.RideDetail'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.User'),
        ),
    ]
