# Generated by Django 3.0.7 on 2021-02-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20210207_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetail',
            name='owner_email',
            field=models.CharField(default='334455@duke.edu', max_length=200),
        ),
    ]
