# Generated by Django 3.0.7 on 2021-02-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_ridedetail_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedetail',
            name='owner_email',
            field=models.CharField(default='mosiqi1996@hotmail.com', max_length=200),
        ),
    ]
